# Actuator - Management
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'beans'
  info:
    env:
      enabled: true

# Info - Actuator Content
info:
  app:
    name: "SpringBoot3-Demo"
    version: "1.0.0"
  developers:
    - "Max"
    - "Rose"

# Spring Security - Configuration
spring:
  security:
    user:
      name: 'admin'
      password: 'secret'

# SLF4J - Configuration
logging:
  level:
    org:
      springframework: 'ERROR'
      springstudent:
        demoproject: 'TRACE'